[build]
  # Set base directory to client folder
  base = "client"
  # Command to build the frontend (now runs from client directory)
  command = "npx vite build"
  # Directory to publish (relative to base directory)
  publish = "dist"

[build.environment]
  # Make sure Netlify uses the API URL
  VITE_API_URL = "https://artisanaljewels.onrender.com"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200